import { neon } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-http';
import { personaggi } from '../shared/schema.js';

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle(sql);

// Lista completa dei PERSONAGGI con PTI e stelle esatti
const personaggiData = `AL BANO, 1250 PTI, 2 STELLE
ALBERTO ANGELA, 2000 PTI, 3 STELLE
AMADEUS, 750 PTI, 3 STELLE
ANDREA, 1000 PTI, 4 STELLE
APE, 150 PTI, 3 STELLE
APOLLO, 1800 PTI, 2 STELLE
ARAGOSTA IRACHENA, 320 PTI, 3 STELLE
AVVOLTOIO, 100 PTI, 1 STELLA
BAMBOLA DEL DEMONIO, 666 PTI, 0 STELLE
BARBONE, 400 PTI, 1 STELLA
BEAR, 1500 PTI, 3 STELLE
BELLO FIGO GU, 200 PTI, 2 STELLE
BERLUSCONI, 1994 PTI, 4 STELLE
BIG DABOL, 700 PTI, 2 STELLE
BIGFOOT, 990 PTI, 2 STELLE
BIMBAMINKIA, 5 PTI, 4 STELLE
BIN LADEN, 1000 PTI, 2 STELLE
BISTECCONE, 350 PTI, 2 STELLE
BOLDI BUILDING, 1000 PTI, 2 STELLE
BORGARALLY, 400 PTI, 0 STELLE
BOSCAIOLO, 800 PTI, 3 STELLE
BRIAN, 400 PTI, 2 STELLE
BRUNO BARBIERI, 520 PTI, 2 STELLE
BUD SPENCER, 1200 PTI, 3 STELLE
BUGS VANNI, ? PTI, 0 STELLE
BULLOX, 2400 PTI, 3 STELLE
CACCA, 500 PTI, 1 STELLA
CACCIATORE STRABICO, 370 PTI, 2 STELLE
CAIFA, 1500 PTI, 3 STELLE
CANNAVACCIUOLO, 1400 PTI, 2 STELLE
CANNUCCIA, 150 PTI, 1 STELLA
CAPELLO & SMITH, 1200+1200 PTI, 3+3 STELLE
CAPO RABBINO, 1200 PTI, 2 STELLE
CELLVINI, 500 PTI, 1 STELLA
CHUCK NORRIS, 3000 PTI, 4 STELLE
CICCHETTI, 2000 PTI, 3 STELLE
CICCIO PANCETTA, 100 PTI, 1 STELLA
CIMICE, 80 PTI, 3 STELLE
CINESE COMUNE, 500 PTI, 1 STELLA
CINGHIALE INFEROCITO, 2300 PTI, 3 STELLE
CIRO PIZZAIOLO DI SFIDUCIA, 600 PTI, 2 STELLE
C-MASTROTA, 400 PTI, 2 STELLE
CRAPA, 550 PTI, 2 STELLE
CRASH BANDICOOT, 700 PTI, 2 STELLE
CYBER GEENA, 1011 PTI, 0 STELLE
DADDY CONTE, 1000 PTI, 2 STELLE
DE MARINIS, 800 PTI, 2 STELLE
DIVINO JOHNNY, 2900 PTI, 4 STELLE
DJIDJI D'ALESSIO, 1200 PTI, 2 STELLE
DON GIULIANO LEELLLEE, 1000 PTI, 3 STELLE
DONALD TRUMP, 800 PTI, 3 STELLE
EEGEENEO MASSAREE, 1900 PTI, 4 STELLE
EMIS KILLA, 800 PTI, 3 STELLE
ENRICO PAPEEIY, 970 PTI, 3 STELLE
EVIL FAKE, 666 PTI, 1 STELLA
EZIO GREGGIO, 1200 PTI, 2 STELLE
FABIO FAUZO, 64 PTI, 1 STELLA
FEDESIMO, 10 PTI, 1 STELLA
FOREVER ALONE, 250 PTI, 1 STELLA
FRA MARTINO, 1 PTI, 1 STELLA
FRANCESCO PANDOLFI, 2800 PTI, 3 STELLE
FRANCESCO ROSSI PAOLOZZI, 2500 PTI, 1 STELLA
GERRY SCOTTI, 1100 PTI, 3 STELLE
GHELLER, 900 PTI, 3 STELLE
GIANNI GIGANTI, 3000 PTI, 1 STELLA
GIDI, 700 PTI, 2 STELLE
GIGI PROIETTILE, 500 PTI, 4 STELLE
GIGIBABY777, 777 PTI, 2 STELLE
GIGIONE, 200 PTI, 3 STELLE
GIOVANNI GRANA, 937 PTI, 2 STELLE
GNOMO ARMATO DI ASCIA, 1300 PTI, 2 STELLE
GOD ZILLA, 700 PTI, 2 STELLE
GOGHI, 1200 PTI, 2 STELLE
GOKU, 2500 PTI, 4 STELLE
GOLDEN FREEZER, 2173 PTI, 3 STELLE
HEIHACHI MISHIMA, 2700 PTI, 4 STELLE
HIPPIE, 680 PTI, 1 STELLA
HITLER, 700 PTI, 2 STELLE
HOLLY, 300 PTI, 2 STELLE
HOMER, 200 PTI, 1 STELLA
HORSY, 2400 PTI, 3 STELLE
IL FENOMENO, 100 PTI, 1 STELLA
IL PELUX, 994 PTI, 2 STELLE
IL ZINGARO, 450 PTI, 2 STELLE
JANARA, 300 PTI, 1 STELLA
JO DONATELLO, 430 PTI, 2 STELLE
JOE BASTIANICH, 1105 PTI, 2 STELLE
JOHN CENA, 500 PTI, 1 STELLA
JUSTIN BIEBERON, 120 PTI, 4 STELLE
KIM JONG UN, 900 PTI, 3 STELLE
KULUNGU, 800 PTI, 2 STELLE
LA MAESTRA VANDA, 700 PTI, 2 STELLE
LEENO BANFY, 2300 PTI, 3 STELLE
LOTAIN, 710 PTI, 2 STELLE
LUCA GIURATO, 444 PTI, 2 STELLE
LUCA NERVI, 600 PTI, 1 STELLA
MAESTRO TONINO, 2200 PTI, 3 STELLE
MAGALLY, 0 PTI, 3 STELLE
MAGO LETTERIUS, 666 PTI, 3 STELLE
MAGONE ALEZIO, 1250 PTI, 3 STELLE
MAJIN PUPO, 800 PTI, 3 STELLE
MALGIOGLIO, 170 PTI, 2 STELLE
MANCAZIONE, 1500 PTI, 2 STELLE
MAOOREETIO KOSTANZO, 600 PTI, 2 STELLE
MAZZAMAURIEL, 300 PTI, 1 STELLA
MICHELE TELO, 20 PTI, 4 STELLE
MILHOUSE, 150 PTI, 1 STELLA
MISTER X, ? PTI, ? STELLE
MOHAMED KEBABBARO DI FIDUCIA, 600 PTI, 2 STELLE
MOLISE, 1 PTI, 0 STELLE
MONATTO, 630 PTI, 2 STELLE
MONTAQUILANO, 400 PTI, 2 STELLE
MORTE, 470 PTI, 3 STELLE
MOSCA, 50 PTI, 1 STELLA
MR BEAN, 200 PTI, 1 STELLA
MUSSOLINI, 600 PTI, 2 STELLE
NANO COL MACHETE NORMALE CHE SEMBRA GIGANTE, 30 PTI, ? STELLE
NAPOLETANO, 400 PTI, 2 STELLE
NEENO PHRASSEEKA, 1000 PTI, 3 STELLE
NERO CHE BEVE LA SODA, 999 PTI, 0 STELLE
N E U E R, 500 PTI, 2 STELLE
NEYMAR JUNIOR (versione Piccolo), 1500 PTI, 2 STELLE
NIKO BELLIC, 1800 PTI, 3 STELLE
NOKIA 3310, 3000 PTI, 4 STELLE
O PAPPON, 400 PTI, 2 STELLE
OBAMA, 800 PTI, 2 STELLE
ONE DIRECTION, 110 PTI, 4 STELLE
OPOSSUM CON LA RABBIA, 300 PTI, 3 STELLE
PANINO MALEFICO, 150 PTI, 3 STELLE
PAOLO BITTA, 600 PTI, 1 STELLA
PAP, 500 PTI, 1 STELLA
PARASSITA, 300 PTI, 0 STELLE
PASQUALE S, 800 PTI, 1 STELLA
PEEO, 1954 PTI, 4 STELLE
PETER, 200 PTI, 1 STELLA
PIERO ANGELA CHE FA LA KAMEHAMEHA, 2300 PTI, 2 STELLE
PINGU, 450 PTI, 1 STELLA
PIPPO RAUDO, 510 PTI, 4 STELLE
POLIZIOTTO, 600 PTI, 2 STELLE
POLLON, 450 PTI, 2 STELLE
PONTIUS PILATUS, 800 PTI, 2 STELLE
POPEYE, 900 PTI, 1 STELLA
POSEIDONE, 2000 PTI, 3 STELLE
PROCIONE INSATANATO, 400 PTI, 4 STELLE
PSY, 500 PTI, 4 STELLE
PUTIN, 1000 PTI, 3 STELLE
RAZZI, 500 PTI, 2 STELLE
REAL GEE, 600 PTI, 3 STELLE
RICCIO PIC, 200 PTI, 1 STELLA
ROMINA POWER, 1350 PTI, 0 STELLE
SAIBAIM, 500 PTI, 2 STELLE
SAVERIO, 2300 PTI, 3 STELLE
SCIALLCUAN, 300 PTI, 3 STELLE
SCIMMIA STRAFATTA, 200 PTI, 2 STELLE
SCREAM, 1000 PTI, 3 STELLE
SHORTY, 400 PTI, 2 STELLE
SILVANO, 200 PTI, 1 STELLA
SILVER SILVIO, 411 PTI, 2 STELLE
STALIN, 900 PTI, 2 STELLE
STEWIE, 500 PTI, 3 STELLE
SUPER MARIO, 500 PTI, 2 STELLE
TED, 400 PTI, 2 STELLE
TEETSEEANO, 1200 PTI, 2 STELLE
TERENCE HILL, 1150 PTI, 3 STELLE
THE ROAK, 1000 PTI, 2 STELLE
THE ROCK, 3000 PTI, 4 STELLE
TIZIO JAMAICANO, 400 PTI, 2 STELLE
TIZIO MAFIOSO, 400 PTI, 2 STELLE
TONY TAMMARO, 1200 PTI, 2 STELLE
TRUE MATTARELLA, 2950 PTI, 4 STELLE
VEGETA, 2400 PTI, 4 STELLE
VU CUMPRA, 400 PTI, 1 STELLA
ZANZARA, 50 PTI, 2 STELLE
ZEUS, 2800 PTI, 4 STELLE
ZI VCIENZ, 2300 PTI, 3 STELLE
ZIO GREGORIO, 1700 PTI, 4 STELLE
ZIO MICHELE, 400 PTI, 1 STELLA`;

async function importPersonaggi() {
  console.log('🚀 Importing PERSONAGGI data to database...');
  
  const lines = personaggiData.trim().split('\n');
  let importedCount = 0;
  let skippedCount = 0;
  
  for (const line of lines) {
    try {
      // Parse line format: "NAME, XXX PTI, Y STELLE" or "NAME, XXX PTI, Y STELLA"
      const parts = line.split(',');
      if (parts.length < 3) {
        console.log(`⚠️  Skipping malformed line: ${line}`);
        skippedCount++;
        continue;
      }
      
      const name = parts[0].trim();
      const ptiPart = parts[1].trim();
      const stellePart = parts[2].trim();
      
      // Extract PTI value
      let pti: number | null = null;
      const ptiMatch = ptiPart.match(/(\d+|\?)\s*PTI/);
      if (ptiMatch && ptiMatch[1] !== '?') {
        pti = parseInt(ptiMatch[1]);
      }
      
      // Handle special cases like "1200+1200 PTI"
      if (ptiPart.includes('+')) {
        const sumMatch = ptiPart.match(/(\d+)\+(\d+)\s*PTI/);
        if (sumMatch) {
          pti = parseInt(sumMatch[1]) + parseInt(sumMatch[2]);
        }
      }
      
      // Extract stars value 
      let stars: number | null = null;
      const starsMatch = stellePart.match(/(\d+|\?)\s*STELL[EA]/);
      if (starsMatch && starsMatch[1] !== '?') {
        stars = parseInt(starsMatch[1]);
      }
      
      // Handle special cases like "3+3 STELLE"
      if (stellePart.includes('+')) {
        const sumMatch = stellePart.match(/(\d+)\+(\d+)\s*STELL[EA]/);
        if (sumMatch) {
          stars = parseInt(sumMatch[1]) + parseInt(sumMatch[2]);
        }
      }
      
      // Insert into database
      await db.insert(personaggi).values({
        name,
        pti,
        stars
      }).onConflictDoNothing(); // Skip duplicates
      
      console.log(`✅ Imported: ${name} - PTI: ${pti || '?'}, Stelle: ${stars || '?'}`);
      importedCount++;
      
    } catch (error) {
      console.error(`❌ Error processing line "${line}":`, error);
      skippedCount++;
    }
  }
  
  console.log(`\n📊 Import completed:`);
  console.log(`✅ Successfully imported: ${importedCount} PERSONAGGI`);
  console.log(`⚠️  Skipped: ${skippedCount} entries`);
  console.log(`🎯 Total processed: ${lines.length} lines`);
}

// Run the import
importPersonaggi().catch(console.error);