// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/admin-modal/Cockpit.tsx": () => import("../components/mockups/admin-modal/Cockpit.tsx"),
  "./components/mockups/admin-modal/LibraryGrid.tsx": () => import("../components/mockups/admin-modal/LibraryGrid.tsx"),
  "./components/mockups/admin-modal/WizardFlow.tsx": () => import("../components/mockups/admin-modal/WizardFlow.tsx"),
  "./components/mockups/home-layouts/ActivityFeed.tsx": () => import("../components/mockups/home-layouts/ActivityFeed.tsx"),
  "./components/mockups/home-layouts/BottomNav.tsx": () => import("../components/mockups/home-layouts/BottomNav.tsx"),
  "./components/mockups/home-layouts/CompactList.tsx": () => import("../components/mockups/home-layouts/CompactList.tsx"),
  "./components/mockups/home-layouts/DashboardFirst.tsx": () => import("../components/mockups/home-layouts/DashboardFirst.tsx"),
  "./components/mockups/home-layouts/HeroTray.tsx": () => import("../components/mockups/home-layouts/HeroTray.tsx"),
  "./components/mockups/home-layouts/HorizontalScroll.tsx": () => import("../components/mockups/home-layouts/HorizontalScroll.tsx"),
  "./components/mockups/home-layouts/MagazineGrid.tsx": () => import("../components/mockups/home-layouts/MagazineGrid.tsx"),
  "./components/mockups/home-reimagine/CardFan.tsx": () => import("../components/mockups/home-reimagine/CardFan.tsx"),
  "./components/mockups/home-reimagine/ClashHQ.tsx": () => import("../components/mockups/home-reimagine/ClashHQ.tsx"),
  "./components/mockups/home-reimagine/RetroArcade.tsx": () => import("../components/mockups/home-reimagine/RetroArcade.tsx"),
  "./components/mockups/home-approaches/CommandRadial.tsx": () => import("../components/mockups/home-approaches/CommandRadial.tsx"),
  "./components/mockups/home-approaches/GameMap.tsx": () => import("../components/mockups/home-approaches/GameMap.tsx"),
  "./components/mockups/home-approaches/ProgressionFirst.tsx": () => import("../components/mockups/home-approaches/ProgressionFirst.tsx"),
  "./components/mockups/home-approaches/SwipeMode.tsx": () => import("../components/mockups/home-approaches/SwipeMode.tsx")
};
